name: Deploy Angular App to Production

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: [self-hosted, prod-client]  # Runner local para 'producción'

    steps:
    - name: Comprobando el repositorio
      uses: actions/checkout@v4

    - name: Configurar el agente SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY_PRODUCTION }}

    - name: Ejecutar el script de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no estudiante@10.43.100.206 'bash -s' < ./deploy.sh production
      working-directory: ./  # Establece el directorio de trabajo a la raíz del repositorio

    - name: Comprobar estado de despliegue
      run: |
        ssh -o StrictHostKeyChecking=no estudiante@10.43.100.206 'docker ps'
